/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function cube333Scramble(a: number): void;
export function cube222Scramble(a: number): void;
export function cube444Scramble(): number;
export function cube555Scramble(a: number): void;
export function cube666Scramble(a: number): void;
export function cube777Scramble(a: number): void;
export function cube333bfScramble(a: number): void;
export function cube333fmScramble(a: number): void;
export function cube333ohScramble(a: number): void;
export function clockScramble(a: number): void;
export function megaminxScramble(a: number): void;
export function pyraminxScramble(a: number): void;
export function skewbScramble(a: number): void;
export function sq1Scramble(a: number): void;
export function cube444bfScramble(): number;
export function cube555bfScramble(a: number): void;
export function cube333mbfScramble(a: number, b: number): void;
export function cube333ftScramble(a: number): void;
export function cube333mboScramble(a: number, b: number): void;
export function cube333EOScramble(a: number, b: number, c: number, d: number, e: number): void;
export function cube333DRScramble(a: number, b: number, c: number, d: number, e: number): void;
export function cube333HTRScramble(a: number, b: number, c: number, d: number, e: number): void;
export function cube333JZPScramble(a: number, b: number, c: number, d: number, e: number): void;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_export_1(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number): void;
export function __wbindgen_export_3(a: number, b: number): number;
export function __wbindgen_export_4(a: number, b: number, c: number, d: number): number;
export function __wbindgen_export_5(a: number): void;
export function __wbindgen_export_6(a: number, b: number, c: number, d: number): void;
