name: deploy server

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      DEPLOY_PATH:
        required: true
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "server/**"
      - ".github/workflows/deploy-server.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull
            pnpm install --frozen-lockfile
            pnpm --filter 333.fm-server build
            cd server
            pm2 start ecosystem.config.js
